# source: corpora/curl_fuzzer/test100_2

actions {
  set_option {
    option_id: CURLOPT_URL
    scope: OPTION_SCOPE_DEFAULT
    string_value: "ftp://127.0.0.1:8992/test-100/"
  }
}
connections {
  id: 0
  initial_response {
    payload: "220 Hello!\n"
  }
  on_readable {
    payload: "200 Sure\n"
  }
  on_readable {
    payload: "200 Sure\n"
  }
  on_readable {
    payload: "200 Sure\n"
  }
  on_readable {
    payload: "400 Sure\n"
  }
  on_readable {
    payload: "200 Sure\n"
  }
}
