#!/usr/bin/env python3
"""
Regenerate option manifest artefacts from the supported CURLOPT list.

This script derives, at build time, the numeric values and value kinds of a
curated list of CURLOPTs directly from curl.h, and emits:

* An expanded ``.proto`` file whose ``CurlOptionId`` enum body contains one
  entry per supported option, using curl's own numeric value.
* A C++ ``.inc`` fragment defining ``kOptionManifest[]`` for the fuzzer to
  dispatch on.

Every input and output path is passed on the command line so the script stays
independent of the repository layout and can be invoked directly by CMake.
The implementation uses only the Python standard library.
"""

from __future__ import annotations

import argparse
import dataclasses
import pathlib
import re
import sys
from typing import Dict, Iterable, List

# Base numeric offsets for CURLOPTTYPE_* families. See curl.h.
TYPE_BASE_VALUES: Dict[str, int] = {
    "CURLOPTTYPE_LONG": 0,
    "CURLOPTTYPE_VALUES": 0,
    "CURLOPTTYPE_OBJECTPOINT": 10000,
    "CURLOPTTYPE_STRINGPOINT": 10000,
    "CURLOPTTYPE_SLISTPOINT": 10000,
    "CURLOPTTYPE_CBPOINT": 10000,
    "CURLOPTTYPE_FUNCTIONPOINT": 20000,
    "CURLOPTTYPE_OFF_T": 30000,
    "CURLOPTTYPE_BLOB": 40000,
}

# Default kind derived from the curl type token. Pointer-like families need
# explicit per-option overrides below because they cover too many shapes.
BASE_KIND: Dict[str, str] = {
    "CURLOPTTYPE_LONG": "uint",
    "CURLOPTTYPE_VALUES": "uint",
    "CURLOPTTYPE_STRINGPOINT": "string",
    "CURLOPTTYPE_OFF_T": "uint",
}

# Options whose kind cannot be inferred from the type token alone.
OPTION_KIND_OVERRIDES: Dict[str, str] = {
    "CURLOPT_POSTFIELDS": "string",
    "CURLOPT_FOLLOWLOCATION": "bool",
    "CURLOPT_NOBODY": "bool",
    "CURLOPT_POST": "bool",
    "CURLOPT_HTTPGET": "bool",
    "CURLOPT_HEADER": "bool",
    "CURLOPT_FAILONERROR": "bool",
    "CURLOPT_AUTOREFERER": "bool",
    "CURLOPT_HTTP09_ALLOWED": "bool",
}

VALUE_KIND_SYMBOLS: Dict[str, str] = {
    "string": "OptionValueKind::kString",
    "uint": "OptionValueKind::kUint",
    "bool": "OptionValueKind::kBool",
}


@dataclasses.dataclass(frozen=True)
class CurlOption:
    name: str
    type_token: str
    curl_value: int

    @property
    def kind(self) -> str:
        resolved = OPTION_KIND_OVERRIDES.get(self.name, BASE_KIND.get(self.type_token))
        if resolved is None:
            raise ValueError(
                f"No kind mapping for {self.name} ({self.type_token}). "
                "Extend BASE_KIND or OPTION_KIND_OVERRIDES."
            )
        return resolved


def load_supported_options(path: pathlib.Path) -> List[str]:
    options: List[str] = []
    for raw_line in path.read_text().splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#"):
            continue
        options.append(line)
    if not options:
        raise ValueError(f"No options found in {path}")
    return options


def parse_curl_header(path: pathlib.Path) -> Dict[str, CurlOption]:
    text = path.read_text()
    pattern = re.compile(
        r"CURLOPT(?:DEPRECATED)?\(\s*"
        r"(CURLOPT_[A-Z0-9_]+)\s*,\s*"
        r"(CURLOPTTYPE_[A-Z0-9_]+)\s*,\s*"
        r"([0-9]+)"
    )
    options: Dict[str, CurlOption] = {}
    for match in pattern.finditer(text):
        name, type_token, offset_text = match.groups()
        if type_token not in TYPE_BASE_VALUES:
            raise ValueError(f"Unknown CURLOPT type token {type_token} for {name}")
        options[name] = CurlOption(
            name=name,
            type_token=type_token,
            curl_value=TYPE_BASE_VALUES[type_token] + int(offset_text),
        )
    if not options:
        raise ValueError(f"No CURLOPT definitions found in {path}")
    return options


def render_manifest(entries: Iterable[CurlOption]) -> str:
    lines = [
        "// Generated by src/curl_fuzzer_tools/generate_option_manifest.py.",
        "// Do not edit. Included once from proto_fuzzer/option_apply.cc.",
        "static constexpr OptionDescriptor kOptionManifest[] = {",
    ]
    for option in entries:
        kind_symbol = VALUE_KIND_SYMBOLS[option.kind]
        lines.append(
            f"    {{curl::fuzzer::proto::{option.name}, "
            f'{kind_symbol}, "{option.name}", {option.name}}},'
        )
    lines.append("};")
    lines.append(
        "static constexpr size_t kOptionManifestSize = "
        "sizeof(kOptionManifest) / sizeof(kOptionManifest[0]);"
    )
    return "\n".join(lines) + "\n"


def render_proto(entries: Iterable[CurlOption], template_text: str) -> str:
    begin = "// GENERATED-OPTIONS-BEGIN"
    end = "// GENERATED-OPTIONS-END"
    begin_idx = template_text.find(begin)
    end_idx = template_text.find(end)
    if begin_idx == -1 or end_idx == -1 or end_idx < begin_idx:
        raise ValueError(
            "Proto template missing GENERATED-OPTIONS markers; expected "
            f"{begin!r} followed by {end!r}."
        )
    head = template_text[: begin_idx + len(begin)]
    tail = template_text[end_idx:]
    body = "\n".join(f"  {opt.name} = {opt.curl_value};" for opt in entries)
    return f"{head}\n{body}\n  {tail}"


def parse_args(argv: List[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--curl-header", required=True, type=pathlib.Path)
    parser.add_argument("--supported-list", required=True, type=pathlib.Path)
    parser.add_argument("--proto-template", required=True, type=pathlib.Path)
    parser.add_argument("--proto-out", required=True, type=pathlib.Path)
    parser.add_argument("--manifest-out", required=True, type=pathlib.Path)
    return parser.parse_args(argv)


def write_if_changed(path: pathlib.Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    if path.exists() and path.read_text() == content:
        return
    path.write_text(content)


def run(argv: List[str] | None = None) -> int:
    args = parse_args(sys.argv[1:] if argv is None else argv)

    supported = load_supported_options(args.supported_list)
    header_options = parse_curl_header(args.curl_header)

    ordered: List[CurlOption] = []
    for name in supported:
        if name not in header_options:
            raise KeyError(
                f"CURLOPT {name} (from {args.supported_list}) "
                f"not found in {args.curl_header}."
            )
        ordered.append(header_options[name])

    template_text = args.proto_template.read_text()
    write_if_changed(args.proto_out, render_proto(ordered, template_text))
    write_if_changed(args.manifest_out, render_manifest(ordered))
    return 0


if __name__ == "__main__":
    raise SystemExit(run())
