# source: corpora/curl_fuzzer_http/test_invalid_prior_http2

actions {
  set_option {
    option_id: CURLOPT_URL
    scope: OPTION_SCOPE_DEFAULT
    string_value: "http://127.0.0.1"
  }
}
actions {
  set_option {
    option_id: CURLOPT_HTTP_VERSION
    scope: OPTION_SCOPE_DEFAULT
    uint32_value: 5
  }
}
connections {
  id: 0
  initial_response {
    payload: "this is not valid"
  }
}
