# source: corpora/curl_fuzzer_http/test4

actions {
  set_option {
    option_id: CURLOPT_URL
    scope: OPTION_SCOPE_DEFAULT
    string_value: "http://127.0.0.1:8990/4"
  }
}
actions {
  add_header {
    value {
      text: "extra-header: here"
    }
  }
}
actions {
  add_header {
    value {
      text: "Accept: replaced"
    }
  }
}
actions {
  add_header {
    value {
      text: "X-Custom-Header;"
    }
  }
}
actions {
  add_header {
    value {
      text: "X-Test: foo;"
    }
  }
}
actions {
  add_header {
    value {
      text: "X-Test:"
    }
  }
}
actions {
  add_header {
    value {
      text: "X-Test2: foo;"
    }
  }
}
actions {
  add_header {
    value {
      text: "X-Test3:  "
    }
  }
}
actions {
  add_header {
    value {
      text: "X-Test4;  "
    }
  }
}
actions {
  add_header {
    value {
      text: "X-Test5;ignored"
    }
  }
}
connections {
  id: 0
  initial_response {
    payload: "HTTP/1.1 200 OK\nDate: Thu, 09 Nov 2010 14:49:00 GMT\nServer: test-server/fake swsclose\nContent-Type: text/html\nFunny-head: yesyes\n\n"
  }
}
