# source: corpora/curl_fuzzer_https/test_altsvc_with_cache

actions {
  set_option {
    option_id: CURLOPT_URL
    scope: OPTION_SCOPE_DEFAULT
    string_value: "https://0x7F000001?foobar.json"
  }
}
actions {
  add_header {
    value {
      text: "Alt-Svc: h3-25=\":4430\"; ma=0"
    }
  }
}
actions {
  add_header {
    value {
      text: "Connection: Keep-Alive"
    }
  }
}
actions {
  add_header {
    value {
      text: "Authorization: Basic aaaaaaaaaaaaaaaaaaa"
    }
  }
}
connections {
  id: 0
  initial_response {
    payload: "HTTPS/2 200 OK"
  }
}
