# Minimal HTTP/1.1 GET with a canned 200 OK response body.
options { option_id: CURLOPT_URL string_value: "http://127.0.0.1/basic" }
connection {
  initial_response: "HTTP/1.1 200 OK\r\nContent-Length: 5\r\nContent-Type: text/plain\r\n\r\nhello"
}
