#!/usr/bin/env bash

FUZZ_TARGETS_LIST="curl_fuzzer_dict curl_fuzzer_file curl_fuzzer_ftp curl_fuzzer_gopher curl_fuzzer_http curl_fuzzer_https curl_fuzzer_imap curl_fuzzer_ldap curl_fuzzer_mqtt curl_fuzzer_pop3 curl_fuzzer_rtsp curl_fuzzer_smb curl_fuzzer_smtp curl_fuzzer_tftp curl_fuzzer_ws curl_fuzzer fuzz_url fuzz_bufq fuzz_doh"

# The structured fuzzer is 64-bit only.
if [ "${ARCHITECTURE:-}" != "i386" ]; then
    FUZZ_TARGETS_LIST="${FUZZ_TARGETS_LIST} curl_fuzzer_proto curl_fuzzer_proto_http curl_fuzzer_proto_http_deep curl_fuzzer_proto_https curl_fuzzer_proto_h2_proxy curl_fuzzer_proto_ws curl_fuzzer_proto_wss curl_fuzzer_proto_telnet curl_fuzzer_proto_ftp curl_fuzzer_proto_tftp curl_fuzzer_proto_api curl_fuzzer_proto_multi curl_fuzzer_proto_timing"
fi

export FUZZ_TARGETS="${FUZZ_TARGETS_LIST}"
