#!/bin/bash

# Handled by renovate.json
OPENSSL_VERSION=openssl-3.2.0

# Handled by renovate.json
QUICTLS_VERSION=openssl-3.1.4-quic1

# renovate: datasource=github-tags depName=nghttp2/nghttp2 versioning=semver registryUrl=https://github.com
NGHTTP2_VERSION=v1.58.0

# renovate: datasource=github-tags depName=ngtcp2/nghttp3 versioning=semver registryUrl=https://github.com
NGHTTP3_VERSION=v1.1.0

# renovate: datasource=github-tags depName=ngtcp2/ngtcp2 versioning=semver registryUrl=https://github.com
NGTCP2_VERSION=v1.1.0
