#!/bin/bash

# Handled by renovate.json
OPENSSL_VERSION=openssl-3.2.0

# renovate: datasource=github-tags depName=nghttp2/nghttp2 versioning=semver registryUrl=https://github.com
NGHTTP2_VERSION=v1.58.0
